// Muxy/Resources/starter-kits/react/src/app.tsx
import { useEffect, useState } from "react";

export function App() {
  const [refreshes, setRefreshes] = useState(0);

  useEffect(() => {
    const off = muxy.events.subscribe("command.refresh-hello", () => setRefreshes((n) => n + 1));
    return () => off?.();
  }, []);

  return (
    <div className="panel">
      <div className="title">Hello from Muxy</div>
      <p className="caption">A starter panel that follows the theme and the sizing scale.</p>
      <div className="card">
        <span>Refreshes</span>
        <span className="count">{refreshes}</span>
      </div>
      <button className="button" onClick={() => setRefreshes((n) => n + 1)}>
        Refresh
      </button>
    </div>
  );
}

// Muxy/Resources/starter-kits/svelte/src/App.svelte
<script lang="ts">
  import { onDestroy } from "svelte";

  let refreshes = $state(0);
  const off = muxy.events.subscribe("command.refresh-hello", () => (refreshes += 1));

  onDestroy(() => off?.());
</script>

<div class="panel">
  <div class="title">Hello from Muxy</div>
  <p class="caption">A starter panel that follows the theme and the sizing scale.</p>
  <div class="card">
    <span>Refreshes</span>
    <span class="count">{refreshes}</span>
  </div>
  <button class="button" onclick={() => (refreshes += 1)}>Refresh</button>
</div>
