// Muxy/Resources/starter-kits/vue/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";

const refreshes = ref(0);
let off: (() => void) | undefined;

onMounted(() => {
  off = muxy.events.subscribe("command.refresh-hello", () => (refreshes.value += 1));
});

onUnmounted(() => off?.());
</script>

<template>
  <div class="panel">
    <div class="title">Hello from Muxy</div>
    <p class="caption">A starter panel that follows the theme and the sizing scale.</p>
    <div class="card">
      <span>Refreshes</span>
      <span class="count">{{ refreshes }}</span>
    </div>
    <button class="button" @click="refreshes += 1">Refresh</button>
  </div>
</template>

// Muxy/Resources/starter-kits/react/src/app.tsx
import { useEffect, useState } from "react";

export function App() {
  const [refreshes, setRefreshes] = useState(0);

  useEffect(() => {
    const off = muxy.events.subscribe("command.refresh-hello", () => setRefreshes((n) => n + 1));
    return () => off?.();
  }, []);

  return (
    <div className="panel">
      <div className="title">Hello from Muxy</div>
      <p className="caption">A starter panel that follows the theme and the sizing scale.</p>
      <div className="card">
        <span>Refreshes</span>
        <span className="count">{refreshes}</span>
      </div>
      <button className="button" onClick={() => setRefreshes((n) => n + 1)}>
        Refresh
      </button>
    </div>
  );
}
